name: Test, Build and Deploy

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main

env:
  DEMO_PATH: ./demo
  DIST_ARTIFACT: demo-build-artifacts

jobs:
  # Set the job key. The key is displayed as the job name when a job name is not provided.
  main:
    # Name the Job
    name: 'Job: Test useFetch'
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install and build
        run: |
          npm ci
          npm run test

  demo_site:
    name: 'Job: Test and build demo site'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install, test and build
        working-directory: ${{ env.DEMO_PATH }}
        run: |
          npm ci
          npm run test
          npm run build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.DIST_ARTIFACT }}
          path: ${{ env.DEMO_PATH }}/dist

  deploy:
    name: 'Job: Deploy demo site'
    runs-on: ubuntu-latest
    needs: [main, demo_site]
    env:
      DIST_PATH: ./dist
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.DIST_ARTIFACT }}
          path: ${{ env.DIST_PATH }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DIST_PATH }}
